# Generated by Django 6.0 on 2026-08-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('ATENDENTE', 'Atendente'), ('SOLICITANTE', 'Solicitante')], default='SOLICITANTE', max_length=15)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
